# Generated by Django 4.2 on 2023-05-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('fees', models.IntegerField()),
                ('duration', models.CharField(default='1', max_length=200)),
                ('desc', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AddStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=255, null=True)),
                ('semail', models.EmailField(blank=True, max_length=255, null=True)),
                ('smobile', models.IntegerField(blank=True, default='0', null=True)),
                ('scollege', models.CharField(default='anything', max_length=255)),
                ('sdegree', models.CharField(default='anything', max_length=255)),
                ('scourse', models.CharField(blank=True, default='anything', max_length=255, null=True)),
                ('sfees', models.IntegerField(blank=True, default='0', null=True)),
                ('sduration', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('saddress', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('sfile', models.FileField(blank=True, default='noselect', null=True, upload_to='')),
                ('scourses', models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.addcourses')),
            ],
        ),
    ]
