# Generated by Django 4.2 on 2023-05-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudents',
            name='sfile',
        ),
    ]
