# Generated by Django 4.2 on 2023-05-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_addstudents_sfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstudents',
            name='scourse',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='sduration',
        ),
        migrations.RemoveField(
            model_name='addstudents',
            name='sfees',
        ),
    ]
