# Generated by Django 4.2 on 2023-05-17 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_addstudents_scourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('temail', models.EmailField(max_length=100)),
                ('tmobile', models.IntegerField()),
                ('taddress', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
